# Generated by Django 5.2.5 on 2025-08-13 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer_text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('question_id_in_barem', models.CharField(help_text='Ví dụ: Q1, Q2...', max_length=20, verbose_name='ID câu hỏi trong tệp barem')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên môn học')),
                ('subject_code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn học')),
                ('quiz_data_file', models.CharField(blank=True, help_text='Ví dụ: data_analysis_quiz.json', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='exam_sessions', to='qna.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(verbose_name='Nội dung trả lời')),
                ('score', models.FloatField(verbose_name='Điểm số')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Nhận xét của AI')),
                ('analysis', models.JSONField(null=True, verbose_name='Phân tích chi tiết')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('follow_up_question', models.TextField(blank=True, null=True, verbose_name='Câu hỏi phụ')),
                ('follow_up_transcript', models.TextField(blank=True, null=True, verbose_name='Nội dung trả lời câu hỏi phụ')),
                ('follow_up_score', models.FloatField(default=0.0, verbose_name='Điểm câu hỏi phụ')),
                ('follow_up_feedback', models.TextField(blank=True, null=True, verbose_name='Nhận xét câu hỏi phụ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='qna.examsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qna.subject', verbose_name='Môn học'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
