# Generated by Django 5.2.5 on 2025-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_supplementary',
            field=models.BooleanField(default=False, verbose_name='Là câu hỏi phụ'),
        ),
    ]
