# Generated by Django 5.2.5 on 2025-08-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_question_is_supplementary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementaryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('transcript', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=1.0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_results', to='qna.examsession')),
            ],
        ),
    ]
