# Generated by Django 5.2.5 on 2025-08-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_supplementaryresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='follow_up_feedback',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='follow_up_question',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='follow_up_score',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='follow_up_transcript',
        ),
        migrations.AddField(
            model_name='examsession',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='Phân tích chi tiết'),
        ),
    ]
