# Generated by Django 5.2.5 on 2025-08-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_remove_examresult_follow_up_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
