# Generated by Django 5.2.5 on 2025-08-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_remove_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
