# Generated by Django 5.2.5 on 2025-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_delete_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
