# Generated by Django 5.2.5 on 2025-09-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0008_userprofile_is_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='qna.subject'),
        ),
    ]
