# Generated by Django 5.2.5 on 2026-01-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0009_userprofile_subjects_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='face_image_blob',
            field=models.BinaryField(blank=True, null=True, verbose_name='Ảnh khuôn mặt chụp từ webcam'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='face_image_mime',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type ảnh khuôn mặt'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='id_card_image_blob',
            field=models.BinaryField(blank=True, null=True, verbose_name='Ảnh thẻ sinh viên'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='id_card_image_mime',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type ảnh thẻ'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='needs_manual_review',
            field=models.BooleanField(default=False, verbose_name='Cần kiểm tra thủ công'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='verification_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm tương đồng (0-1)'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác thực'), ('ALLOW', 'Cho phép thi'), ('WARNING_ALLOW', 'Cho phép thi (cần kiểm tra lại)'), ('BLOCK', 'Chặn thi')], default='PENDING', max_length=20, verbose_name='Trạng thái xác thực'),
        ),
    ]
