# Generated by Django 5.2.5 on 2026-01-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0010_examsession_face_image_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_password',
            field=models.CharField(blank=True, help_text='Mật khẩu để sinh viên vào bài thi (để trống nếu không cần)', max_length=100, null=True, verbose_name='Mật khẩu bài thi'),
        ),
    ]
