# Generated by Django 5.2.5 on 2026-01-11 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0011_subject_exam_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('room_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phòng')),
                ('capacity', models.PositiveIntegerField(verbose_name='Sức chứa')),
            ],
            options={
                'verbose_name': 'Phòng thi',
                'verbose_name_plural': 'Phòng thi',
                'ordering': ['room_code'],
            },
        ),
        migrations.CreateModel(
            name='ExamCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100, verbose_name='Tên mã đề')),
                ('source_material', models.TextField(blank=True, null=True, verbose_name='Nguồn tài liệu')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Đã duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('question_easy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_codes_easy', to='qna.question', verbose_name='Câu hỏi Dễ')),
                ('question_hard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_codes_hard', to='qna.question', verbose_name='Câu hỏi Khó')),
                ('question_medium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_codes_medium', to='qna.question', verbose_name='Câu hỏi Trung bình')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_codes', to='qna.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Mã đề thi',
                'verbose_name_plural': 'Mã đề thi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSessionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Tên ca thi')),
                ('exam_date', models.DateTimeField(verbose_name='Ngày giờ thi')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Thời gian làm bài (phút)')),
                ('exam_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mật khẩu bài thi')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SCHEDULED', 'Đã lên lịch'), ('ONGOING', 'Đang diễn ra'), ('COMPLETED', 'Đã kết thúc'), ('CANCELLED', 'Đã hủy')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exam_groups', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('exam_codes', models.ManyToManyField(related_name='exam_session_groups', to='qna.examcode', verbose_name='Mã đề thi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_session_groups', to='qna.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Ca thi',
                'verbose_name_plural': 'Ca thi',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='qna.examsessiongroup', verbose_name='Ca thi'),
        ),
        migrations.CreateModel(
            name='ExamSessionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rooms', to='qna.examsessiongroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rooms', to='qna.examroom')),
                ('students', models.ManyToManyField(related_name='exam_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Phòng thi trong ca thi',
                'verbose_name_plural': 'Phòng thi trong ca thi',
            },
        ),
        migrations.AddField(
            model_name='examsessiongroup',
            name='rooms',
            field=models.ManyToManyField(through='qna.ExamSessionRoom', to='qna.examroom', verbose_name='Phòng thi'),
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề tài liệu')),
                ('file_path', models.CharField(max_length=500, verbose_name='Đường dẫn file')),
                ('file_type', models.CharField(max_length=50, verbose_name='Loại file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_materials', to='qna.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Tài liệu bài giảng',
                'verbose_name_plural': 'Tài liệu bài giảng',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
