# Generated by Django 6.0.3 on 2026-03-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0012_examroom_examcode_examsessiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Trung bình'), ('HARD', 'Khó')], default='EASY', max_length=10, verbose_name='Độ khó'),
        ),
    ]
