# Generated by Django 6.0.3 on 2026-03-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0013_question_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_id_in_barem']},
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
    ]
